/**
 * @file     usb.h (180.ARM_Peripherals/Project_Headers/usb.h)
 * @brief    Universal Serial Bus
 *
 * @version  V4.12.1.210
 * @date     13 April 2016
 *      Author: podonoghue
 */

#ifndef HEADER_USB_H
#define HEADER_USB_H
/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include <stdio.h>
#include <cstring>
#include "hardware.h"
#include "usb_defs.h"
#include "utilities.h"
#include "usb_endpoint.h"

namespace USBDM {

/**
 * @addtogroup USB_Group USB, USB OTG Controller
 * @brief Abstraction for USB OTG Controller
 * @{
 */

/**
 * Base class representing an USB Interface.\n
 * Holds shared constants and utility functions.
 */
class UsbBase {

public:
   /**
    * Device Status
    */
   struct DeviceStatus {
      int selfPowered  : 1;    //!< Device is self-powered
      int remoteWakeup : 1;    //!< Supports remote wake-up
      int portTest     : 1;    //!< Port test
      int res1         : 5;    //!< Reserved
      int res2         : 8;    //!< Reserved
   };

   /**
    * Endpoint Status in USB format
    */
   struct EndpointStatus {
      int stall  : 1;   //!< Endpoint is stalled
      int res1   : 7;   //!< Reserved
      int res2   : 8;   //!< Reserved
   };

   /**
    * Events for user callback
    */
   enum UserEvents {
      USER_SUSPEND,  //!< USB has been suspended
      USER_RESUME,   //!< USB has been resumed
      USER_RESET,    //!< USB has been reset
   };

   /**
    * Type definition for user call back\n
    * This function is called whenever the 'user' code needs to be notified of an event
    *
    *  @param[in]  event Reason for callback
    *
    *  @return Error code
    */
   typedef ErrorCode (*UserCallbackFunction)(const UserEvents event);

   /**
    * Type definition for USB SOF call back\n
    * This function is call for SOF transactions
    */
   typedef ErrorCode (*SOFCallbackFunction)();

   /**
    * Type definition for user call back\n
    * This function is called whenever the 'user' code needs to be notified of an event
    *
    *  @param[in]  event Reason for callback
    */
   typedef void (*SetupCompleteCallbackFunction)();

   /**
    * Type definition for USB SETUP call back\n
    * This function is called for SETUP transactions not automatically handled
    *
    *  @param[in]  setup SETUP packet information
    */
   typedef ErrorCode (*SetupCallbackFunction)(const SetupPacket &setup);

   /**
    * Dummy callback used to catch use of unset required callback
    */
   static ErrorCode unsetHandlerCallback() {
      return setAndCheckErrorCode(E_NO_HANDLER);
   }

   /**
    * Dummy callback used catch use of unset optional callback
    */
   static ErrorCode unsetOptionalHandlerCallback() {
      return E_NO_HANDLER;
   }

   /**
    * Get name of USB token
    *
    * @param[in]   token USB token
    *
    * @return Pointer to static string
    */
   static const char *getTokenName(unsigned token);

   /**
    * Get name of USB state
    *
    * @param[in]   state USB state
    *
    * @return Pointer to static string
    */
   static const char *getStateName(EndpointState state);

   /**
    * Get name of USB request
    *
    * @param[in]   reqType Request type
    *
    * @return Pointer to static string
    */
   static const char *getRequestName(uint8_t reqType);

   /**
    * Report contents of BDT
    *
    * @param[in]  name    Descriptive name to use
    * @param[in]  bdt     BDT to report
    */
   static void reportBdt(const char *name, BdtEntry *bdt);

   /**
    * Report contents of LineCodingStructure to stdout
    *
    * @param lineCodingStructure
    */
   void reportLineCoding(const LineCodingStructure *lineCodingStructure);

   /**
    * Format SETUP packet as string
    *
    * @param[in]  p SETUP packet
    *
    * @return Pointer to static buffer
    */
   static const char *reportSetupPacket(SetupPacket *p);

   /**
    * Report line state value to stdout
    *
    * @param value
    */
   void reportLineState(uint8_t value);

   /**
    *  Creates a valid string descriptor in UTF-16-LE from a limited UTF-8 string
    *
    *  @param[in]  to       Where to place descriptor
    *  @param[in]  from     Zero terminated UTF-8 C string
    *  @param[in]  maxSize  Size of destination
    *
    *  @note Only handles UTF-8 characters that fit in a single UTF-16 value.
    */
   static void utf8ToStringDescriptor(uint8_t *to, const uint8_t *from, unsigned maxSize);
};

/**
 * Class representing a USB Interface
 *
 * @tparam Info      USB info class
 * @tparam EP0_SIZE  Size of EP0 endpoint transactions
 */
template <class Info, int EP0_SIZE>
class UsbBase_T : public UsbBase {

protected:
   /** Clock register for peripheral */
   static __attribute__((always_inline)) volatile uint32_t &fClockReg() { return Info::clockReg(); }

public:
   /** Hardware instance pointer */
   static __attribute__((always_inline)) volatile USB_Type &fUsb() { return Info::usb(); }

protected:
   /** USB Control endpoint number - must be zero */
   static constexpr int CONTROL_ENDPOINT = 0;

   /** USB Control endpoint - always EP0 */
   static ControlEndpoint<Info, EP0_SIZE>fControlEndpoint;

   /** Magic number for MS driver feature */
   static constexpr uint8_t MS_VENDOR_CODE = 0x30;

   /** Magic string for MS driver feature */
   static const     uint8_t fMsOsStringDescriptor[];

   /** End-points in use */
   static Endpoint *fEndPoints[];

   /** Mask for all USB interrupts */
   static constexpr uint8_t USB_INTMASKS =
         USB_INTEN_STALLEN_MASK|
         USB_INTEN_SLEEPEN_MASK|
         USB_INTEN_TOKDNEEN_MASK|
         USB_INTEN_SOFTOKEN_MASK|
         USB_INTEN_USBRSTEN_MASK;

   /** USB connection state */
   static volatile DeviceConnectionStates fConnectionState;

   /** Active USB configuration */
   static uint8_t fDeviceConfiguration;

   /** USB Device status */
   static DeviceStatus fDeviceStatus;

   /** Buffer for EP0 Setup packet (copied from USB RAM) */
   static SetupPacket fEp0SetupBuffer;

   /** USB activity indicator */
   static volatile bool fActivityFlag;

   /**
    * Unhandled SETUP callback \n
    * This function is called for unhandled SETUP transactions
    */
   static SetupCallbackFunction fUnhandledSetupCallback;

   /**
    * User event callback \n
    * This function is called whenever the 'user' code needs to be notified of an event
    *
    *  @param[in]  event Reason for callback
    *  @return     E_NOERROR if handled
    *  @return     Else stalls endpoint
    */
   static UserCallbackFunction fUserCallbackFunction;

   /**
    * SETUP complete callback\n
    * This function is called when SETUP transaction is complete
    */
   static SetupCompleteCallbackFunction fSetupCompleteCallback;

   /**
    * Start-of-frame callback \n
    * This function is called when SOF transaction is complete
    */
   static SOFCallbackFunction fSofCallbackFunction;

   /** Used to record Suspend/Resume events */
   static int fSuspendCounter;
   
public:
   /**
    * Configures all mapped pins associated with this peripheral
    */
   static void __attribute__((always_inline)) configureAllPins() {
      // Configure pins
      Info::initPCRs();
   }

   /**
    * Initialise USB to default settings\n
    * Configures all USB pins
    */
   static void enable() {
      fClockReg() |= Info::clockMask;
      __DMB();

      configureAllPins();

      enableNvicInterrupts();
   }

   /**
    * Enable/disable interrupts in NVIC
    *
    * @param[in]  enable        True => enable, False => disable
    * @param[in]  nvicPriority  Interrupt priority
    */
   static void enableNvicInterrupts(bool enable=true, uint32_t nvicPriority=NvicPriority_Normal) {

      if (enable) {
         enableNvicInterrupt(Info::irqNums[0], nvicPriority);
      }
      else {
         // Disable interrupts
         NVIC_DisableIRQ(Info::irqNums[0]);
      }
   }

   /**
    * Enable/disable interrupts
    *
    * @param[in]  mask Mask of interrupts to enable e.g. USB_INTEN_SOFTOKEN_MASK, USB_INTEN_STALLEN_MASK etc
    */
   static void enableInterrupts(uint8_t mask=0xFF) {
      fUsb().INTEN = mask;
   }

   /**
    * Enable/disable OTG interrupts
    *
    * @param[in]  mask Mask of interrupts to enable e.g. USB_OTGICR_IDEN_MASK, USB_OTGICR_ONEMSECEN_MASK etc
    */
   static void enableOtgInterrupts(uint8_t mask=0xFF) {
      fUsb().OTGICR = mask;
   }

   /**
    * Checks if the USB device is configured i.e. connected and enumerated etc.
    *
    * @return true if configured
    */
   static bool isConfigured() {
      return fConnectionState == USBconfigured;
   }

protected:
   /**
    * Callback used for EP0 transaction complete
    *
    * @param[in]  state State active immediately before call-back\n
    * (End-point state is currently EPIdle)
    */
   static void ep0TransactionCallback(EndpointState state);

   /**
    * Does base initialisation of the USB interface
    *
    *  @note Assumes clock set up for USB operation (48MHz)
    */
   static void initialise();

   /**
    * Adds an endpoint.
    *
    * @param[in]  endpoint The end-point to add
    */
   static void addEndpoint(Endpoint *endpoint);

   /**
    * Set the USB activity flag
    *
    * @param[in]  busy True to indicates there was recent activity
    */
   static void setActive(bool busy=true) {
      fActivityFlag = busy;
   }

   /**
    * Set callback for user callback\n
    * This function is called whenever the 'user' code needs to be notified of an event
    *
    *  @param[in]  callback User callback function
    */
   static void setUserCallback(UserCallbackFunction callback) {
      if (callback == nullptr) {
         callback = unsetHandlerCallback;
      }
      fUserCallbackFunction = callback;
   }

   /**
    * Set callback for unhandled SETUP transactions
    *
    * @param[in]  callback The call-back function to execute
    */
   static void setUnhandledSetupCallback(SetupCallbackFunction callback) {
      if (callback == nullptr) {
         callback = (SetupCallbackFunction)unsetHandlerCallback;
      }
      fUnhandledSetupCallback = callback;
   }

   /**
    *  Sets the function to call when SETUP transaction is complete
    *
    * @param[in]  callback The call-back function to execute\n
    *                      May be nullptr to remove callback
    */
   static void setSetupCompleteCallback(SetupCompleteCallbackFunction callback) {
      if (callback == nullptr) {
         callback = (SetupCompleteCallbackFunction)unsetOptionalHandlerCallback;
      }
      fSetupCompleteCallback = callback;
   }

   /**
    * Set callback for SOF transactions
    *
    * @param[in]  callback The call-back function to execute\n
    *                      May be nullptr to remove callback
    */
   static void setSOFCallback(SOFCallbackFunction callback) {
      if (callback == nullptr) {
         callback = unsetOptionalHandlerCallback;
      }
      fSofCallbackFunction = callback;
   }

   /**
    * Configure EP0 for a status IN transactions [Tx, device -> host, DATA0/1]\n
    * Used to acknowledge a DATA out transaction
    */
   static void ep0TxStatus() {
      fControlEndpoint.startTxTransaction(EPStatusIn);
   }

   /**
    * Configure EP0 for a series of IN transactions [Tx, device -> host, DATA0/1]\n
    * This will be in response to a SETUP transaction\n
    * The data may be split into multiple DATA0/DATA1 packets
    *
    * @param[in]  bufSize Size of buffer to send
    * @param[in]  bufPtr  Pointer to buffer (may be NULL to indicate fControlEndpoint.fDatabuffer is being used directly)
    */
   static void ep0StartTxTransaction(uint16_t bufSize, const uint8_t *bufPtr) {
      if (bufSize > fEp0SetupBuffer.wLength) {
         // More data than requested in SETUP request - truncate
         bufSize = (uint8_t)fEp0SetupBuffer.wLength;
      }
      // If short response we may need ZLP
      fControlEndpoint.setNeedZLP(bufSize < fEp0SetupBuffer.wLength);
      fControlEndpoint.startTxTransaction(EPDataIn, bufSize, bufPtr);
   }

   /**
    * Configure EP0-out for a SETUP transaction [Rx, device<-host, DATA0]\n
    * Endpoint state is changed to EPIdle
    * There is no external buffer associated with this transaction.
    */
   static void ep0ConfigureSetupTransaction() {
      // Set up EP0-RX to Rx SETUP packets
      fControlEndpoint.startRxTransaction(EPIdle);
   }

   /**
    * Set USB interface to default state
    */
   static void setUSBdefaultState() {
      fConnectionState      = USBdefault;
      fUsb().ADDR            = 0;
      fDeviceConfiguration  = 0;
      fSuspendCounter       = 0;
   }

   /**
    * Set addressed state
    *
    * @param[in]  address The USB address to set
    */
   static void setUSBaddressedState( uint8_t address ) {
      if (address == 0) {
         // Unaddress??
         setUSBdefaultState();
      }
      else {
         fConnectionState       = USBaddressed;
         fUsb().ADDR             = address;
         fDeviceConfiguration   = 0;
      }
   }

   /**
    * Set configures state
    *
    * @param[in]  config The number of the configuration to set
    */
   static void setUSBconfiguredState( uint8_t config ) {
      if (config == 0) {
         // unconfigure
         setUSBaddressedState(fUsb().ADDR);
      }
      else {
         fConnectionState      = USBconfigured;
         fDeviceConfiguration  = config;
      }
   }

   /**
    * Initialises EP0 and clears other end-points
    */
   static void initialiseEndpoints(void);

   /**
    * Handles SETUP Packet
    */
   static void handleSetupToken();

   /**
    * Handler for Token Complete USB interrupt for EP0\n
    * Handles fControlEndpoint [SETUP, IN & OUT]
    *
    * @return true indicates token has been processed.\n
    * false token still needs processing
    */
   static bool handleTokenComplete();

   /**
    * Handler for USB Bus reset\n
    * Re-initialises the interface
    */
   static void handleUSBReset();

   /**
    * STALL completed - re-enable fControlEndpoint for SETUP
    */
   static void handleStallComplete() {
      fControlEndpoint.clearStall();
      ep0ConfigureSetupTransaction();
   }

   /**
    * Handler for Start of Frame Token interrupt (~1ms interval)
    */
   static void handleSOFToken() {
      fSofCallbackFunction();
   }

   /**
    * Handler for USB Suspend
    *   - Enables the USB module to wake-up the CPU
    *   - Stops the CPU
    * On wake-up
    *   - Re-checks the USB after a small delay to avoid wake-ups by noise
    *   - The RESUME interrupt is left pending so the resume handler can execute
    */
   static void handleUSBSuspend();

   /**
    * Handler for USB Resume
    *
    * Disables further USB module wake-ups
    */
   static void handleUSBResume();

   /**
    * Handles unexpected SETUP requests on EP0 \n
    * Call unhandledSetupCallback() if initialised \n
    */
   static void handleUnexpectedSetup() {
      if (fUnhandledSetupCallback(fEp0SetupBuffer) != E_NO_ERROR) {
         PRINTF("handleUnexpectedSetup(%s)\n", reportSetupPacket(&fEp0SetupBuffer));
         fControlEndpoint.stall();
      }
   }

   /**
    * Does user event callback \n
    * This function is called whenever the 'user' code needs to be notified of an event
    *
    *  @param[in]  event Reason for callback
    */
   static void handleUserCallback(UserEvents event) {
      fUserCallbackFunction(event);
   }

   /**
    * Get Status - Device Request 0x00
    */
   static void handleGetStatus();

   /**
    * Clear Feature - Device Request 0x01
    */
   static void handleClearFeature();

   /**
    * Set Feature - Device Request 0x03
    */
   static void handleSetFeature();

   /**
    * Get Descriptor - Device Request 0x06
    */
   static void handleGetDescriptor();

   /**
    * Set device Address - Device Request 0x05
    */
   static void handleSetAddress() {
      static uint8_t newAddress;

      if (fEp0SetupBuffer.bmRequestType != (EP_OUT|RT_DEVICE)) {// Out,Standard,Device
         // Illegal format - stall fControlEndpoint
         fControlEndpoint.stall();
         return;
      }

      // Record address for callback
      newAddress = fEp0SetupBuffer.wValue.lo();

      // Setup callback to update address at end of transaction
      static auto callback = []() {
         setUSBaddressedState(newAddress);
         //PRINTF("setAddresscb - %d\n", newAddress);
      };
      setSetupCompleteCallback(callback);

      ep0TxStatus(); // Tx empty Status packet
   }

   /**
    * Get Configuration - Device Request 0x08
    */
   static void handleGetConfiguration() {
      static uint8_t temp = fDeviceConfiguration;
      ep0StartTxTransaction( 1, &temp );
   }

   /**
    * Set Configuration - Device Request 0x09
    * Treated as soft reset
    */
   static void handleSetConfiguration();

   /**
    * Set interface - Device Request 0x0B
    * Not required to be implemented
    */
   static void handleSetInterface();

   /**
    * Get interface - Device Request 0x0A
    */
   static void handleGetInterface() {
      static const uint8_t interfaceAltSetting = 0;

      //   PUTS("getInterface");

      if ((fEp0SetupBuffer.bmRequestType != (EP_IN|RT_INTERFACE)) || // NOT In,Standard,Interface
            (fEp0SetupBuffer.wLength != 1)) {                        // NOT correct length
         fControlEndpoint.stall(); // Error
         return;
      }
      // Send packet
      ep0StartTxTransaction( sizeof(interfaceAltSetting), &interfaceAltSetting );
   }

public:
   static void irqHandler();

};

/** Suspend/resume callback */
template<class Info, int EP0_SIZE>
int UsbBase_T<Info, EP0_SIZE>::fSuspendCounter = 0;

/**
 * Start-of-frame callback \n
 * This function is called when SOF transaction is complete
 */
template<class Info, int EP0_SIZE>
UsbBase::SOFCallbackFunction UsbBase_T<Info, EP0_SIZE>::fSofCallbackFunction = nullptr;

/**
 * User event callback \n
 * This function is called whenever the 'user' code needs to be notified of an event
 *
 *  @param[in]  event Reason for callback
 */
template<class Info, int EP0_SIZE>
UsbBase::UserCallbackFunction UsbBase_T<Info, EP0_SIZE>::fUserCallbackFunction = nullptr;

/**
 * Unhandled SETUP callback \n
 * This function is called for unhandled SETUP transactions
 */
template<class Info, int EP0_SIZE>
UsbBase::SetupCallbackFunction UsbBase_T<Info, EP0_SIZE>::fUnhandledSetupCallback = nullptr;

/**
 * SETUP complete callback \n
 * This function is called when SETUP transaction is complete
 */
template <class Info, int EP0_SIZE>
UsbBase::SetupCompleteCallbackFunction UsbBase_T<Info, EP0_SIZE>::fSetupCompleteCallback = nullptr;

/** USB connection state */
template<class Info, int EP0_SIZE>
volatile DeviceConnectionStates UsbBase_T<Info, EP0_SIZE>::fConnectionState;

/** Active USB configuration */
template<class Info, int EP0_SIZE>
uint8_t UsbBase_T<Info, EP0_SIZE>::fDeviceConfiguration;

/** USB Device status */
template<class Info, int EP0_SIZE>
UsbBase::DeviceStatus UsbBase_T<Info, EP0_SIZE>::fDeviceStatus;

/** Buffer for EP0 Setup packet (copied from USB RAM) */
template<class Info, int EP0_SIZE>
SetupPacket UsbBase_T<Info, EP0_SIZE>::fEp0SetupBuffer;

/** USB activity indicator */
template<class Info, int EP0_SIZE>
volatile bool UsbBase_T<Info, EP0_SIZE>::fActivityFlag = false;

/** USB Control endpoint - always EP0 */
template <class Info, int EP0_SIZE>
ControlEndpoint<Info, EP0_SIZE> UsbBase_T<Info, EP0_SIZE>::fControlEndpoint;

} // End namespace USBDM

/*
 * Implementation class
 */
#include "usb_implementation.h"

/*
 * Implementation of methods for UsbBase_T
 */
namespace USBDM {

/** End-points in use */
template <class Info, int EP0_SIZE>
Endpoint *UsbBase_T<Info, EP0_SIZE>::fEndPoints[UsbImplementation::NUMBER_OF_ENDPOINTS];

#if defined(MS_COMPATIBLE_ID_FEATURE)
template<class Info, int EP0_SIZE>
const uint8_t UsbBase_T<Info, EP0_SIZE>::fMsOsStringDescriptor[] = {
      18, DT_STRING, 'M',0,'S',0,'F',0,'T',0,'1',0,'0',0,'0',0,MS_VENDOR_CODE,0x00
};

// UTF16LE strings
#define MS_DEVICE_INTERFACE_GUIDs u"DeviceInterfaceGUIDs"
#define MS_DEVICE_GUID            u"{93FEBD51-6000-4E7E-A20E-A80FC78C7EA1}"
#define MS_ICONS                  u"Icons"
#define MS_ICON_PATH              u"%SystemRoot%\\system32\\shell32.dll,-233"

#pragma pack(push, 2)
struct MS_PropertiesFeatureDescriptor {
   /*----------------------- Header ------------------------------*/
   uint32_t lLength;                //!< Size of this Descriptor in Bytes
   uint16_t wVersion;               //!< Version
   uint16_t wIndex;                 //!< Index (must be 5)
   uint16_t bnumSections;           //!< Number of property sections
   /*---------------------- Section 1 -----------------------------*/
   uint32_t lPropertySize0;          //!< Size of property section
   uint32_t ldataType0;              //!< Data type 1 = Unicode REG_SZ etc
   uint16_t wNameLength0;            //!< Length of property name
   char16_t bName0[sizeof(MS_DEVICE_INTERFACE_GUIDs)/sizeof(MS_DEVICE_INTERFACE_GUIDs[0])];
   uint32_t wPropertyLength0;        //!< Length of property data
   char16_t bData0[sizeof(MS_DEVICE_GUID)/sizeof(MS_DEVICE_GUID[0])];
   /*---------------------- Section 2 -----------------------------*/
   uint32_t lPropertySize1;          //!< Size of property section
   uint32_t ldataType1;              //!< Data type 1 = Unicode REG_SZ etc
   uint16_t wNameLength1;            //!< Length of property name
   char16_t bName1[sizeof(MS_ICONS)/sizeof(MS_ICONS[0])];
   uint32_t wPropertyLength1;        //!< Length of property data
   char16_t bData1[sizeof(MS_ICON_PATH)/sizeof(MS_ICON_PATH[0])];
};
#pragma pack(pop)

#endif

extern const MS_CompatibleIdFeatureDescriptor msCompatibleIdFeatureDescriptor;
extern const MS_PropertiesFeatureDescriptor   msPropertiesFeatureDescriptor;

/**
 * Handles SETUP Packet
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleSetupToken() {

   // Save data from SETUP packet
   memcpy(&fEp0SetupBuffer, fControlEndpoint.getBuffer(), sizeof(fEp0SetupBuffer));

   // Tell endpoint about the SETUP pkt
   fControlEndpoint.setupReceived();

   // Call-backs only persist during a SETUP transaction
   setSetupCompleteCallback(nullptr);

//   PRINTF("handleSetupToken(%s)\n", reportSetupPacket(&fEp0SetupBuffer));

   switch(REQ_TYPE(fEp0SetupBuffer.bmRequestType)) {
      case REQ_TYPE_STANDARD :
         // Standard device requests
         switch (fEp0SetupBuffer.bRequest) {
            case GET_STATUS :          handleGetStatus();            break;
            case CLEAR_FEATURE :       handleClearFeature();         break;
            case SET_FEATURE :         handleSetFeature();           break;
            case SET_ADDRESS :         handleSetAddress();           break;
            case GET_DESCRIPTOR :      handleGetDescriptor();        break;
            case GET_CONFIGURATION :   handleGetConfiguration();     break;
            case SET_CONFIGURATION :   handleSetConfiguration();     break;
            case SET_INTERFACE :       handleSetInterface();         break;
            case GET_INTERFACE :       handleGetInterface();         break;
            case SET_DESCRIPTOR :
            case SYNCH_FRAME :
            default :                  handleUnexpectedSetup();           break;
         }
         break;

      case REQ_TYPE_CLASS :
         // Class requests
         handleUnexpectedSetup();
         break;

      case REQ_TYPE_VENDOR :
         // Handle special commands here
         switch (fEp0SetupBuffer.bRequest) {
#ifdef MS_COMPATIBLE_ID_FEATURE
            case MS_VENDOR_CODE :
               //               PUTS("REQ_TYPE_VENDOR - VENDOR_CODE");
               if (fEp0SetupBuffer.wIndex == 0x0004) {
                  //                  PUTS("REQ_TYPE_VENDOR - MS_CompatibleIdFeatureDescriptor");
                  ep0StartTxTransaction(sizeof(MS_CompatibleIdFeatureDescriptor), (const uint8_t *)&msCompatibleIdFeatureDescriptor);
               }
               else if (fEp0SetupBuffer.wIndex == 0x0005) {
                  //                  PUTS("REQ_TYPE_VENDOR - MS_PropertiesFeatureDescriptor");
                  ep0StartTxTransaction(sizeof(MS_PropertiesFeatureDescriptor), (const uint8_t *)&msPropertiesFeatureDescriptor);
               }
               else {
                  handleUnexpectedSetup();
               }
               break;
#endif

            default :
               handleUnexpectedSetup();
               break;
         }
      break;

      case REQ_TYPE_OTHER :
         handleUnexpectedSetup();
         break;
   }
   // In case another SETUP packet
   fControlEndpoint.initialiseBdtRx();

   // Allow transactions post SETUP packet (clear TXSUSPENDTOKENBUSY)
   fUsb().CTL = USB_CTL_USBENSOFEN_MASK;
}

/**
 * Handler for Token Complete USB interrupt for EP0\n
 * Handles fControlEndpoint [SETUP, IN & OUT]
 *
 * @return true   Token has been processed (control endpoint).\n
 * @return false  Token still needs processing (data endpoint).
 */
template<class Info, int EP0_SIZE>
bool UsbBase_T<Info, EP0_SIZE>::handleTokenComplete() {
   // Status from Token
   uint8_t usbStat  = fUsb().STAT;

   // Endpoint number
   uint8_t endPoint = ((uint8_t)usbStat)>>4;

   if (endPoint != CONTROL_ENDPOINT) {
      // Hasn't been processed
      return false;
   }
   fControlEndpoint.flipOddEven(usbStat);

   // Relevant BDT
   BdtEntry *bdt = &bdts[usbStat>>2];

   // Control - Accept SETUP, IN or OUT token
#if 0
   if (bdt->u.result.tok_pid == SETUPToken) {
      PUTS("\n=====");
   }
   PRINTF("\nTOKEN=%s, STATE=%s, size=%d, %s, %s, %s\n",
         getTokenName(bdt->u.result.tok_pid),
         getStateName(fControlEndpoint.getHardwareState().state),
         bdt->bc,
         (usbStat&USB_STAT_TX_MASK)?"Tx":"Rx",
               bdt->u.result.data0_1?"DATA1":"DATA0",
                     (usbStat&USB_STAT_ODD_MASK)?"Odd":"Even");
#endif
   switch (bdt->u.result.tok_pid) {
      case SETUPToken:
         handleSetupToken();
         break;
      case INToken:
         fControlEndpoint.handleInToken();
         break;
      case OUTToken:
         fControlEndpoint.handleOutToken();
         break;
      default:
         PRINTF("Unexpected token on EP0 = %s\n", getTokenName(bdt->u.result.tok_pid));
         break;
   }
   // Indicate processed
   return true;
}

/**
 * Handler for USB Bus reset\n
 * Re-initialises the interface
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleUSBReset() {
//   PUTS("\nReset");

   // Disable all interrupts
   fUsb().INTEN = 0x00;
   fUsb().ERREN = 0x00;

   // Clear USB error flags
   fUsb().ERRSTAT = 0xFF;

   // Clear most USB interrupt flags
   fUsb().ISTAT = (uint8_t)~USB_ISTAT_TOKDNE_MASK;
   
   // Set initial USB state
   setUSBdefaultState();

   // Initialise control end-point
   initialiseEndpoints();

   // Enable various interrupts
   fUsb().INTEN = USB_INTMASKS|USB_INTEN_ERROREN_MASK;
   fUsb().ERREN = 0xFF;
}

/*
 * Handler for USB Suspend
 *   - Enables the USB module to wake-up the CPU
 *   - Stops the CPU
 * On wake-up
 *   - Re-checks the USB after a small delay to avoid wake-ups by noise
 *   - The RESUME interrupt is left pending so the resume handler can execute
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleUSBSuspend() {
//   PUTS("Suspend");
   if (fConnectionState != USBconfigured) {
      // Ignore if not configured
      return;
   }
   if (++fSuspendCounter<3) {
      // ignore
      return;
   }

   // Asynchronous Resume Interrupt Enable (USB->CPU)
   // Only enable if transceiver is disabled
   //   fUsb().USBTRC0  |= USB_USBTRC0_USBRESMEN_MASK;

   // Enable resume detection or reset interrupts from the USB
   fUsb().INTEN   |= (USB_INTEN_RESUMEEN_MASK|USB_INTEN_USBRSTEN_MASK);
   fConnectionState = USBsuspended;

   // Notify user level (to enter Low power later!!!)
   handleUserCallback(USER_SUSPEND);
   return;
}

/**
 * Handler for USB Resume
 *
 * Disables further USB module wake-ups
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleUSBResume() {
//   PUTS("Resume");

   if (--fSuspendCounter>0) {
      // Ignore as may be noise
      return;
   }
   fSuspendCounter = 0;

   // Mask further resume interrupts
   fUsb().INTEN   &= ~USB_INTEN_RESUMEEN_MASK;

   if (fConnectionState != USBsuspended) {
      // Ignore if not suspended
      return;
   }

   fConnectionState = USBconfigured;

   // Notify user
   handleUserCallback(USER_RESUME);

   // Initialise all end-points
   initialiseEndpoints();
   UsbImplementation::initialiseEndpoints();

   // Enable the transmit or receive of packets
   fUsb().CTL = USB_CTL_USBENSOFEN_MASK;
}

/**
 * Callback used for EP0 transaction complete
 *
 * @param[in]  state State active immediately before call-back\n
 * (End-point state is currently EPIdle)
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::ep0TransactionCallback(EndpointState state) {
   switch (state) {
      case EPDataOut:
         // Just completed a series of OUT transfers on EP0 -
         // Now idle - make sure ready for SETUP reception
         ep0ConfigureSetupTransaction();
         // Do empty status packet transmission - no response expected
         ep0TxStatus();
         break;
      case EPDataIn:
         // Just completed a series of IN transfers on EP0 -
         // Do empty status packet reception
         fControlEndpoint.startRxTransaction(EPStatusOut);
         break;
      case EPStatusIn:
         // Just completed an IN transaction acknowledging a series of OUT transfers -
         // SETUP transaction is complete
         // Do SETUP transaction complete callback
         fSetupCompleteCallback();
         break;
      case EPStatusOut:
         // Just completed an OUT transaction acknowledging a series of IN transfers -
         // Now idle - make sure ready for SETUP reception
         ep0ConfigureSetupTransaction();
         break;
      default:
         PRINTF("Unhandled %d\n", state);
         break;
   }

}

/**
 * Does base initialisation of the USB interface
 *
 *  @note Assumes clock set up for USB operation (48MHz)
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::initialise() {
   enable();

   fSofCallbackFunction    = unsetOptionalHandlerCallback;
   fSetupCompleteCallback  = (SetupCompleteCallbackFunction)unsetHandlerCallback;
   fUnhandledSetupCallback = (SetupCallbackFunction)unsetOptionalHandlerCallback;
   fUserCallbackFunction   = (UserCallbackFunction)unsetHandlerCallback;

   // Make sure no interrupt during setup
   enableNvicInterrupts(false);

   fUsb().OTGISTAT = 0;
   fUsb().OTGICR   = 0;
   fUsb().OTGCTL   = 0;
   fUsb().INTEN    = 0;
   fUsb().ERRSTAT  = 0;
   fUsb().ERREN    = 0;
   fUsb().CTL      = 0;
   fUsb().ADDR     = 0;
   for (unsigned i=0; i<(sizeof(fUsb().ENDPOINT)/sizeof(fUsb().ENDPOINT[0])); i++) {
      fUsb().ENDPOINT[i].ENDPT = 0;
   }
   fUsb().USBCTRL = 0;
   fUsb().CONTROL = 0;
   fUsb().USBTRC0 = 0;

#ifdef MPU_CESR_VLD_MASK
   // Disable MPU & clear errors
   MPU->CESR = MPU_CESR_SPERR_MASK;
#endif

   // Enable USB regulator
   SIM->SOPT1CFG  = SIM_SOPT1CFG_URWE_MASK;
   SIM->SOPT1    |= SIM_SOPT1_USBREGEN_MASK;

#ifdef USB_CLK_RECOVER_IRC_EN_IRC_EN
   // IRC clock enable
   fUsb().CLK_RECOVER_IRC_EN = Usb0Info::clk_recovery_irc_en;

   // Clock recovery options
   fUsb().CLK_RECOVER_CTRL = Usb0Info::clk_recovery_ctrl;
#endif

#if 0
   // Enable in LP modes
   SIM->SOPT1CFG  = SIM_SOPT1CFG_URWE_MASK;
   SIM->SOPT1    &= ~(SIM_SOPT1_USBSSTBY_MASK|SIM_SOPT1_USBVSTBY_MASK);
#endif

#if 0
   // Removed due to errata e5928: USBOTG: USBx_USBTRC0[USBRESET] bit does not operate as expected in all cases
   // Reset USB H/W
   USB0_USBTRC0 |= USB_USBTRC0_USBRESET_MASK;
   while ((USB0_USBTRC0&USB_USBTRC0_USBRESET_MASK) != 0) {
   }
#endif

   // This bit is undocumented but seems to be necessary
   fUsb().USBTRC0 = 0x40;

   // Point USB at BDT array
   fUsb().BDTPAGE3 = (uint8_t) (((unsigned)endPointBdts)>>24);
   fUsb().BDTPAGE2 = (uint8_t) (((unsigned)endPointBdts)>>16);
   fUsb().BDTPAGE1 = (uint8_t) (((unsigned)endPointBdts)>>8);

   // Clear all pending interrupts
   fUsb().ISTAT = 0xFF;

   // Enable fUsb reset interrupt
   fUsb().INTEN = USB_INTEN_USBRSTEN_MASK|USB_INTEN_SLEEPEN_MASK;

   // Weak pull downs
   fUsb().USBCTRL = USB_USBCTRL_PDE_MASK;

   // Enable Pull-up
   fUsb().CONTROL = USB_CONTROL_DPPULLUPNONOTG_MASK;

   // Enable interface
   fUsb().CTL = USB_CTL_USBENSOFEN_MASK;

   // Set initial USB state
   setUSBdefaultState();

   // Initialise control end-point
   initialiseEndpoints();

   // Enable USB interrupts
   enableNvicInterrupts();
}

/**
 * Adds an endpoint.
 *
 * @param[in]  endpoint The end-point to add
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::addEndpoint(Endpoint *endpoint) {
   fEndPoints[endpoint->fEndpointNumber] = endpoint;
}

/**
 * Initialise control end-point.\n
 * Clears other end-points
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::initialiseEndpoints() {

   //   PUTS("initialiseEndpoints()");

   // Clear all BDTs
   memset((uint8_t*)(endPointBdts), 0, sizeof(EndpointBdtEntry[UsbImplementation::NUMBER_OF_ENDPOINTS]));

   // Clear odd/even bits & enable USB device
   fUsb().CTL = USB_CTL_USBENSOFEN_MASK|USB_CTL_ODDRST_MASK;
   fUsb().CTL = USB_CTL_USBENSOFEN_MASK;

   fControlEndpoint.initialise();

   fControlEndpoint.setCallback(ep0TransactionCallback);

   // Set up to receive SETUP packet
   ep0ConfigureSetupTransaction();
}

/**
 * Get Status - Device Request 0x00
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleGetStatus() {

//   PRINTF("handleGetStatus()\n");

   static const uint8_t        zeroReturn[]    = {0,0};
   static const EndpointStatus epStatusStalled = {1,0,0};
   static const EndpointStatus epStatusOK      = {0,0,0};

   const uint8_t *dataPtr = nullptr;
   uint8_t size;
   uint8_t epNum;

   switch(fEp0SetupBuffer.bmRequestType) {
      case EP_IN|RT_DEVICE : // Device Status
      dataPtr = (uint8_t *) &fDeviceStatus;
      size    = sizeof(fDeviceStatus);
      break;

      case EP_IN|RT_INTERFACE : // Interface Status - reserved
      dataPtr = zeroReturn;
      size = sizeof(zeroReturn);
      break;

      case EP_IN|RT_ENDPOINT : // Endpoint Status
      epNum = fEp0SetupBuffer.wIndex&0x07;
      if (epNum <= UsbImplementation::NUMBER_OF_ENDPOINTS) {
         if (fUsb().ENDPOINT[epNum].ENDPT&USB_ENDPT_EPSTALL_MASK) {
            dataPtr = (uint8_t*)&epStatusStalled;
         }
         else {
            dataPtr = (uint8_t*)&epStatusOK;
         }
         size = sizeof(EndpointStatus);
      }
      break;
   }
   if (dataPtr != nullptr) {
      ep0StartTxTransaction( size, dataPtr );
   }
   else {
      fControlEndpoint.stall();
   }
}

/**
 * Clear Feature - Device Request 0x01
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleClearFeature() {
   bool okResponse = false;

   switch(fEp0SetupBuffer.bmRequestType) {
      case RT_DEVICE : // Device Feature
         if ((fEp0SetupBuffer.wValue != DEVICE_REMOTE_WAKEUP) || // Device remote wake up
               (fEp0SetupBuffer.wIndex != 0))   {                // Device index must be 0
            break;
         }
         fDeviceStatus.remoteWakeup = 0;
         okResponse                = true;
         break;

      case RT_INTERFACE : // Interface Feature
         break;

      case RT_ENDPOINT : { // Endpoint Feature ( Out,Standard,Endpoint )
         uint8_t epNum = fEp0SetupBuffer.wIndex&0x07;
         if ((fEp0SetupBuffer.wValue != ENDPOINT_HALT) || // Not Endpoint Stall ?
               (epNum >= UsbImplementation::NUMBER_OF_ENDPOINTS))  { // or illegal EP# (ignores direction)
            break;
         }
         assert(fEndPoints[epNum] != nullptr);
         fEndPoints[epNum]->clearStall();
         okResponse = true;
      }
      break;

      default : // Illegal
         break;
   }

   if (okResponse) {
      ep0TxStatus(); // Tx empty Status packet
   }
   else {
      fControlEndpoint.stall();
   }
}

/**
 * Set Feature - Device Request 0x03
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleSetFeature() {
   bool okResponse = false;

   switch(fEp0SetupBuffer.bmRequestType) {
      case RT_DEVICE : // Device Feature
         if ((fEp0SetupBuffer.wValue != DEVICE_REMOTE_WAKEUP) || // Device remote wakeup
               (fEp0SetupBuffer.wIndex != 0)) {                  // device wIndex must be 0
            break;
         }
         fDeviceStatus.remoteWakeup = 1;
         okResponse                      = true;
         break;

      case RT_INTERFACE : // Interface Feature
         break;

      case RT_ENDPOINT : { // Endpoint Feature ( Out,Standard,Endpoint )
         uint8_t epNum = fEp0SetupBuffer.wIndex&0x07;
         if ((fEp0SetupBuffer.wValue != ENDPOINT_HALT) || // Not Endpoint Stall ?
               (epNum >= UsbImplementation::NUMBER_OF_ENDPOINTS))  {                   // or illegal EP# (ignores direction)
            break;
         }
         assert(fEndPoints[epNum] != nullptr);
         fEndPoints[epNum]->stall();
         okResponse = true;
      }
      break;

      default : // Illegal
         break;
   }
   if (okResponse) {
      ep0TxStatus(); // Tx empty Status packet
   }
   else {
      fControlEndpoint.stall();
   }
}

/**
 * Get Descriptor - Device Request 0x06
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleGetDescriptor() {
   unsigned        descriptorIndex = fEp0SetupBuffer.wValue.lo();
   uint16_t        dataSize = 0;
   const uint8_t  *dataPtr = nullptr;

//   PRINTF("handleGetDescriptor(%d:%d)\n", fEp0SetupBuffer.wValue.hi(), fEp0SetupBuffer.wValue.lo());

   if (fEp0SetupBuffer.bmRequestType != (EP_IN|RT_DEVICE)) {
      // Must be In,Standard,Device
      fControlEndpoint.stall();
      return;
   }
   switch (fEp0SetupBuffer.wValue.hi()) {

      case DT_DEVICE: // Get Device Descriptor - 1
         //      PUTS("getDescriptor-device - ");
         dataPtr  = (uint8_t *) &UsbImplementation::deviceDescriptor;
         dataSize = sizeof(UsbImplementation::deviceDescriptor);
         break;
      case DT_CONFIGURATION: // Get Configuration Descriptor - 2
         //      PUTS("getDescriptor-config - ");
         if (fEp0SetupBuffer.wValue.lo() != 0) {
            fControlEndpoint.stall();
            return;
         }
         dataPtr  = (uint8_t *) &UsbImplementation::otherDescriptors;
         dataSize = sizeof(UsbImplementation::otherDescriptors);
         break;
      case DT_DEVICEQUALIFIER: // Get Device Qualifier Descriptor
         //      PUTS("getDescriptor-deviceQ - ");
         fControlEndpoint.stall();
         return;
      case DT_STRING: // Get String Desc.- 3
         //      PRINTF("getDescriptor-string - %d\n", descriptorIndex);
#ifdef MS_COMPATIBLE_ID_FEATURE
         if (descriptorIndex == 0xEE) {
            //         PUTS("getDescriptor-string - MS_COMPATIBLE_ID_FEATURE");
            dataPtr  = fMsOsStringDescriptor;
            dataSize = *dataPtr;
            break;
         }
#endif
         if (descriptorIndex >= UsbImplementation::s_number_of_string_descriptors) {
            // Illegal string index - stall
            fControlEndpoint.stall();
            return;
         }
         if (descriptorIndex == 0) {
            // Language bytes (unchanged)
            dataPtr  = UsbImplementation::stringDescriptors[0];
         }
#if defined(UNIQUE_ID)
         else if (descriptorIndex == UsbImplementation::s_serial_index) {
            uint8_t utf8Buff[sizeof(SERIAL_NO)+10];

            // Generate Semi-unique Serial number
            uint32_t uid = SIM->UIDH^SIM->UIDMH^SIM->UIDML^SIM->UIDL;
//            FormattedIO::ltoa(uid, utf8Buff, Radix_10);
            snprintf((char *)utf8Buff, sizeof(utf8Buff), SERIAL_NO, uid);

            // Use end-point internal buffer directly - may result in truncation
            dataPtr = fControlEndpoint.getBuffer();
            utf8ToStringDescriptor(fControlEndpoint.getBuffer(), utf8Buff, fControlEndpoint.BUFFER_SIZE);
         }
#endif
         else {
            // Use end-point internal buffer directly - may result in truncation
            dataPtr = fControlEndpoint.getBuffer();
            utf8ToStringDescriptor(fControlEndpoint.getBuffer(), UsbImplementation::stringDescriptors[descriptorIndex], fControlEndpoint.BUFFER_SIZE);
         }
         dataSize = *dataPtr;
         break;
      default:
         // Shouldn't happen
         fControlEndpoint.stall();
         return;
   } // switch

   // Set up transmission
   ep0StartTxTransaction( dataSize, dataPtr );
}

/**
 * Set Configuration - Device Request 0x09
 * Treated as soft reset
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleSetConfiguration() {
   if ((fEp0SetupBuffer.bmRequestType != (EP_OUT|RT_DEVICE)) || // Out,Standard,Device
         ((fEp0SetupBuffer.wValue.lo() != 0) &&       // Only supports 0=> un-configure, 1=> only valid configuration
               (fEp0SetupBuffer.wValue.lo() != UsbImplementation::CONFIGURATION_NUM))) {
      fControlEndpoint.stall();
      return;
   }
   setUSBconfiguredState(fEp0SetupBuffer.wValue.lo());

   // Initialise non-control end-points
   UsbImplementation::initialiseEndpoints();

   // Tx empty Status packet
   ep0TxStatus();
}

/**
 * Set interface - Device Request 0x0B
 * Not required to be implemented
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::handleSetInterface() {
   PUTS("setInterface");

   if ((fEp0SetupBuffer.bmRequestType != (EP_OUT|RT_INTERFACE)) || // NOT In,Standard,Interface
         (fEp0SetupBuffer.wLength != 0) ||                         // NOT correct length
         (fConnectionState != USBconfigured)) {                  // NOT in addressed state
      fControlEndpoint.stall(); // Error
      return;
   }
   // Only support one Alternate Setting == 0
   if (fEp0SetupBuffer.wValue != 0) {
      fControlEndpoint.stall(); // Error
      return;
   }
   for (int epNum=1; epNum<UsbImplementation::NUMBER_OF_ENDPOINTS; epNum++) {
      // Reset DATA0/1 toggle
      fEndPoints[epNum]->clearStall();
   }
   // Transmit empty Status packet
   ep0TxStatus();
}

/**
 * Handler for USB interrupt
 *
 * Determines source and dispatches to appropriate routine.
 */
template<class Info, int EP0_SIZE>
void UsbBase_T<Info, EP0_SIZE>::irqHandler() {

   //   if (interruptFlags&~USB_ISTAT_SOFTOK_MASK) {
   //      PRINTF("ISTAT=%2X\n", interruptFlags);
   //   }

   do {
      // Get active and enabled flags only
      uint8_t pendingInterruptFlags = fUsb().ISTAT & fUsb().INTEN;

      if (pendingInterruptFlags == 0) {
         return;
      }
      if ((pendingInterruptFlags&USB_ISTAT_USBRST_MASK) != 0) {
         // Reset signaled on Bus
         fUsb().ISTAT = USB_ISTAT_USBRST_MASK; // Clear source
         handleUSBReset();
         return;
      }
      if ((pendingInterruptFlags&USB_ISTAT_TOKDNE_MASK) != 0) {
         // Token complete interrupt
         if (!handleTokenComplete()) {
            // Pass to extension routine
            UsbImplementation::handleTokenComplete();
         }
         /*
          *  Clear source
          *  Must be done after processing token as pops USB0_STAT register
          */
         fUsb().ISTAT = USB_ISTAT_TOKDNE_MASK;
      }
      if ((pendingInterruptFlags&USB_ISTAT_RESUME_MASK) != 0) {
         // Resume signaled on Bus
         handleUSBResume();
         // Clear source
         fUsb().ISTAT = USB_ISTAT_RESUME_MASK;
      }
      if ((pendingInterruptFlags&USB_ISTAT_STALL_MASK) != 0) {
         // Stall sent
         handleStallComplete();
         // Clear source
         fUsb().ISTAT = USB_ISTAT_STALL_MASK;
      }
      if ((pendingInterruptFlags&USB_ISTAT_SOFTOK_MASK) != 0) {
         // SOF Token
         handleSOFToken();
         fUsb().ISTAT = USB_ISTAT_SOFTOK_MASK; // Clear source
      }
      if ((pendingInterruptFlags&USB_ISTAT_SLEEP_MASK) != 0) {
         // Bus Idle 3ms => sleep
         //      PUTS("Suspend");
         handleUSBSuspend();
         // Clear source
         fUsb().ISTAT = USB_ISTAT_SLEEP_MASK;
      }
      if ((pendingInterruptFlags&USB_ISTAT_ERROR_MASK) != 0) {
         // Any Error
         PRINTF("Error s=0x%02X\n", fUsb().ERRSTAT);
         fUsb().ERRSTAT = 0xFF;
         // Clear source
         fUsb().ISTAT = USB_ISTAT_ERROR_MASK;
      }
   } while(true);
}

/**
 * End USB_Group
 * @}
 */

} // End namespace USBDM

#endif /* HEADER_USB_H */
