var modules =
[
    [ "CMSIS Global Defines", "group___c_m_s_i_s__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group___c_m_s_i_s__core__register.html", "group___c_m_s_i_s__core__register" ],
    [ "Functions and Instructions Reference", "group___c_m_s_i_s___core___function_interface.html", "group___c_m_s_i_s___core___function_interface" ],
    [ "CMSIS SIMD Intrinsics", "group___c_m_s_i_s___s_i_m_d__intrinsics.html", null ],
    [ "CMSIS Core Instruction Interface", "group___c_m_s_i_s___core___instruction_interface.html", null ],
    [ "Analogue Input", "group___analogue_i_o___group.html", "group___analogue_i_o___group" ],
    [ "Bit-band access", "group___b_i_t_b_a_n_d__group.html", "group___b_i_t_b_a_n_d__group" ],
    [ "CMP, Analogue Comparator", "group___c_m_p___group.html", "group___c_m_p___group" ],
    [ "FTM, PWM, Input capture and Output compare", "group___f_t_m___group.html", "group___f_t_m___group" ],
    [ "GPIO, Digital Input/Output", "group___g_p_i_o___group.html", "group___g_p_i_o___group" ],
    [ "I2C, Inter-Integrated-Circuit Interface", "group___i2_c___group.html", "group___i2_c___group" ],
    [ "LPTMR, Low Power Timer", "group___l_p_t_m_r___group.html", "group___l_p_t_m_r___group" ],
    [ "MCG, Multipurpose Clock Generator", "group___m_c_g___group.html", "group___m_c_g___group" ],
    [ "Interrupt vector numbers", "group___interrupt__vector__numbers___g_r_o_u_p.html", "group___interrupt__vector__numbers___g_r_o_u_p" ],
    [ "Interrupt handler prototypes", "group___interrupt__handler__prototypes___g_r_o_u_p.html", "group___interrupt__handler__prototypes___g_r_o_u_p" ],
    [ "Cortex Core Configuration", "group___cortex___core___configuration___g_r_o_u_p.html", "group___cortex___core___configuration___g_r_o_u_p" ],
    [ "Device Peripheral Access Layer", "group___peripheral__access__layer___g_r_o_u_p.html", "group___peripheral__access__layer___g_r_o_u_p" ],
    [ "Peripheral Information Classes", "group___peripheral_pin_tables.html", "group___peripheral_pin_tables" ],
    [ "PDB, Programmable Dely Block", "group___p_d_b___group.html", "group___p_d_b___group" ],
    [ "OSC, Crystal Oscillator", "group___o_s_c___group.html", "group___o_s_c___group" ],
    [ "RTC, Real Time Clock", "group___r_t_c___group.html", "group___r_t_c___group" ],
    [ "SIM, System Integration Module", "group___s_i_m___group.html", "group___s_i_m___group" ],
    [ "ADC, Analogue Input", "group___a_d_c___group.html", "group___a_d_c___group" ],
    [ "CMT, Carrier Modulator Transmitter", "group___c_m_t___group.html", "group___c_m_t___group" ],
    [ "CONTROL, Control", "group___control___group.html", "group___control___group" ],
    [ "CRC, (Incomplete)", "group___c_r_c___t_o_d_o___group.html", "group___c_r_c___t_o_d_o___group" ],
    [ "Console, Console", "group___c_o_n_s_o_l_e___group.html", null ],
    [ "DMA, (Incomplete)", "group___d_m_a___t_o_d_o___group.html", "group___d_m_a___t_o_d_o___group" ],
    [ "DMAMUX, Direct Memory Access (DMA)", "group___d_m_a_m_u_x___group.html", "group___d_m_a_m_u_x___group" ],
    [ "EWM, External Watchdog Monitor", "group___e_w_m___group.html", "group___e_w_m___group" ],
    [ "FTFL, (Incomplete)", "group___f_t_f_l___t_o_d_o___group.html", "group___f_t_f_l___t_o_d_o___group" ],
    [ "I2S, Inter-Integrated-Circuit Interface", "group___i2_s___group.html", "group___i2_s___group" ],
    [ "LLWU, Low-leakage Wake-up Unit", "group___l_l_w_u___group.html", "group___l_l_w_u___group" ],
    [ "PIT, Programmable Interrupt Timer", "group___p_i_t___group.html", "group___p_i_t___group" ],
    [ "POWER, Power", "group___power___group.html", "group___power___group" ],
    [ "SMC, System Mode Controller", "group___s_m_c___group.html", "group___s_m_c___group" ],
    [ "SPI, Serial Peripheral Interface", "group___s_p_i___group.html", "group___s_p_i___group" ],
    [ "UART, Universal Asynchronous Receiver/Transmitter", "group___u_a_r_t___group.html", "group___u_a_r_t___group" ],
    [ "USB, USB OTG Controller", "group___u_s_b___group.html", "group___u_s_b___group" ],
    [ "USBDCD, USB Device Charger Detection", "group___u_s_b_d_c_d___group.html", "group___u_s_b_d_c_d___group" ],
    [ "VREF, Voltage Reference", "group___v_r_e_f___group.html", "group___v_r_e_f___group" ]
];