/**
 * @file     pmc.h (180.ARM_Peripherals/Project_Headers/pmc.h)
 * @brief    Power Management Controller
 *
 * @version  V4.12.1.80
 * @date     13 April 2016
 */
#ifndef PMC_H_
#define PMC_H_
 /*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include "hardware.h"

namespace USBDM {

/**
 * Indicates reason for execution of call-back
 */
enum PmcInterruptReason {
   PmcInterruptReason_LowVoltageDetect,//!< Low Voltage Detect
   PmcInterruptReason_LowVoltageWarning//!< Low Voltage Warning
};

/**
 * Type definition for PDB interrupt call back
 *
 * @param pmcInterruptReason Reason for interrupt leading to call-back
 */
typedef void (*PMCCallbackFunction)(PmcInterruptReason pmcInterruptReason);

/**
 * Action to take on Low Voltage Detect
 */
enum PmcLowVoltageDetectAction {
   PmcLowVoltageDetectAction_None      = PMC_LVDSC1_LVDRE(0)|PMC_LVDSC1_LVDIE(0),//!< No action on Low Voltage Detect
   PmcLowVoltageDetectAction_Interrupt = PMC_LVDSC1_LVDRE(1)|PMC_LVDSC1_LVDIE(1),//!< Interrupt on Low Voltage Detect
   PmcLowVoltageDetectAction_Reset     = PMC_LVDSC1_LVDRE(0)|PMC_LVDSC1_LVDIE(0),//!< Reset on Low Voltage Detect
};

/**
 * Level at which Low Voltage Detect operates
 */
enum PmcLowVoltageDetectLevel {
   PmcLowVoltageDetectLevel_Low        = PMC_LVDSC1_LVDV(0),//!< Lowest level - Vlvdl
   PmcLowVoltageDetectLevel_High       = PMC_LVDSC1_LVDV(1),//!< Lowest level - Vlvdh
//   PmcLowVoltageDetectLevel_Reserved1  = PMC_LVDSC1_LVDV(2),//!< Reserved
//   PmcLowVoltageDetectLevel_Reserved2  = PMC_LVDSC1_LVDV(3),//!< Reserved
};

/**
 * Action to take on Low Voltage Warning
 */
enum PmcLowVoltageWarningAction {
   PmcLowVoltageWarningAction_None      = PMC_LVDSC2_LVWIE(0),//!< No action on Low Voltage Warning
   PmcLowVoltageWarningAction_Interrupt = PMC_LVDSC2_LVWIE(1),//!< Interrupt on Low Voltage Warning
};

/**
 * Level at which Low Voltage Warning operates
 */
enum PmcLowVoltageWarningLevel {
   PmcLowVoltageWarningLevel_low    = PMC_LVDSC2_LVWV(0), //!< Lowest level - Vlvw1
   PmcLowVoltageWarningLevel_Mid1   = PMC_LVDSC2_LVWV(1), //!< Low middle - Vlvw2
   PmcLowVoltageWarningLevel_Mid2   = PMC_LVDSC2_LVWV(2), //!< High middle - Vlvw3
   PmcLowVoltageWarningLevel_High   = PMC_LVDSC2_LVWV(3), //!< Highest level - Vlvw4
};

/**
 * Controls when Band-gap reference is available to internal devices e.g. CMP etc.
 */
enum PmcBandgapMode {
   PmcBandgapMode_Off      =                   PMC_REGSC_BGBE(0),//!< Buffer off, band-gap unavailable
   PmcBandgapMode_On       =                   PMC_REGSC_BGBE(0),//!< Buffer on, band-gap unavailable in VLPx, LLSx and VLLSx
#ifdef PMC_REGSC_BGEN
   PmcBandgapMode_AlwaysOn = PMC_REGSC_BGEN(1)|PMC_REGSC_BGBE(1),//!< Buffer on, band-gap available in VLPx, LLSx and VLLSx
#endif
};

/**
 * @addtogroup PMC_Group PMC, Power Management Controller
 * @brief Peripheral information for Power Management Controller
 * @{
 */
/**
 * Template class providing interface to Power Management Controller
 *
 * @tparam info      Information class for PMC
 *
 * @code
 * using pmc = PmcBase_T<PmcInfo>;
 *
 *  pmc::defaultConfigure();
 *
 * @endcode
 */
template <class Info>
class PmcBase_T {

protected:
   /** Callback function for ISR */
   static PMCCallbackFunction callback;
   /** Handler for unexpected interrupts */
   static void illegalInterruptHandler(PmcInterruptReason) {
      setAndCheckErrorCode(E_NO_HANDLER);
   }
public:
   /**
    * IRQ handler
    */
   static void irqHandler(void) {

      if ((PmcBase_T<Info>::pmc->LVDSC1 & (PMC_LVDSC1_LVDF_MASK|PMC_LVDSC1_LVDIE_MASK)) ==
            (PMC_LVDSC1_LVDF_MASK|PMC_LVDSC1_LVDIE_MASK)) {

         // LVDF enabled and detected
         PmcBase_T<Info>::pmc->LVDSC1 |= PMC_LVDSC1_LVDF_MASK;
         callback(PmcInterruptReason_LowVoltageDetect);
         return;
      }
      if ((PmcBase_T<Info>::pmc->LVDSC2 & (PMC_LVDSC2_LVWF_MASK|PMC_LVDSC2_LVWIE_MASK)) ==
            (PMC_LVDSC2_LVWF_MASK|PMC_LVDSC2_LVWIE_MASK)) {

         // LVWF enabled and detected
         PmcBase_T<Info>::pmc->LVDSC2 |= PMC_LVDSC2_LVWF_MASK;
         callback(PmcInterruptReason_LowVoltageWarning);
         return;
      }
#ifdef DEBUG_BUILD
      // Should be impossible
      __BKPT();
#endif
   }

   /**
    * Set Callback function
    *
    *   @param[in]  theCallback - Callback function to be executed on PMC interrupt
    */
   static void setCallback(PMCCallbackFunction theCallback) {
      if (theCallback == nullptr) {
         callback = illegalInterruptHandler;
         return;
      }
      callback = theCallback;
   }


protected:
   static constexpr volatile PMC_Type *pmc      = Info::pmc;

public:
   /**
    * Enable clock to the PMC
    */
   static void  __attribute__((always_inline)) enable() {
   }

   /**
    * Enables PMC and sets to default configuration.
    *
    * Includes enabling clock and any pins used.\n
    * Sets PMC to default configuration.
    */
   static void defaultConfigure() {
      enable();

      pmc->LVDSC1 = Info::pmc_lvdsc1;
      pmc->LVDSC2 = Info::pmc_lvdsc2;
      pmc->REGSC  = Info::pmc_regsc;

      enableNvicInterrupts();
   }

   /**
    * Set action and level for Low Voltage Detect
    *
    * @param[in] pmcLowVoltageDetectAction Action to take on Low Voltage Detect
    * @param[in] pmcLowVoltageDetectLevel  Level at which Low Voltage Detect operates
    */
   static void setResetAction (
         PmcLowVoltageDetectAction pmcLowVoltageDetectAction = PmcLowVoltageDetectAction_None,
         PmcLowVoltageDetectLevel  pmcLowVoltageDetectLevel  = PmcLowVoltageDetectLevel_High
         ) {
      pmc->LVDSC1 = pmcLowVoltageDetectAction|pmcLowVoltageDetectLevel;
   }

   /**
    * Set action and level for Low Voltage Warning
    *
    * @param[in] pmcLowVoltageWarningAction   Action to take on Low Voltage Warning
    * @param[in] pmcLowVoltageWarningLevel    Level at which Low Voltage Warning operates
    */
   static void setWarningAction (
         PmcLowVoltageWarningAction pmcLowVoltageWarningAction = PmcLowVoltageWarningAction_None,
         PmcLowVoltageWarningLevel  pmcLowVoltageWarningLevel  = PmcLowVoltageWarningLevel_High
         ) {
      pmc->LVDSC2 = pmcLowVoltageWarningAction|pmcLowVoltageWarningLevel;
   }

   /**
    * Determines availability of Band-gap reference
    *
    * @param[in] pmcBandgapMode   Controls when Band-gap reference is available to internal devices e.g. CMP etc.
    */
   static void setBangapOperation(PmcBandgapMode pmcBandgapMode=PmcBandgapMode_On) {
      pmc->REGSC = pmcBandgapMode;
   }

   /**
    * Enable/disable interrupts in NVIC
    *
    * @param[in]  enable True => enable, False => disable
    */
   static void enableNvicInterrupts(bool enable=true) {
      if (enable) {
         // Enable interrupts
         NVIC_EnableIRQ(Info::irqNums[0]);

         // Set priority level
         NVIC_SetPriority(Info::irqNums[0], Info::irqLevel);
      }
      else {
         // Disable interrupts
         NVIC_DisableIRQ(Info::irqNums[0]);
      }
   }

};

template<class Info> PMCCallbackFunction PmcBase_T<Info>::callback = PmcBase_T<Info>::illegalInterruptHandler;

#ifdef USBDM_PMC_IS_DEFINED
/**
 * Class representing PMC
 */
using Pmc = PmcBase_T<PmcInfo>;

#endif

#ifdef USBDM_PMC0_IS_DEFINED
/**
 * Class representing PMC
 */
using Pmc = PmcBase_T<PmcInfo>;

#endif

/**
 * End PMC_Group
 * @}
 */
} // End namespace USBDM

#endif /* PMC_H_ */
