/**
 * @file      hardware.cpp (generated from MK22D5.usbdmHardware)
 * @version   1.2.0
 * @brief     Pin initialisation for MK22DX128VLF5
 *
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#include "hardware.h"

/**
 * Namespace enclosing USBDM classes
 */
namespace USBDM {

/**
 * @addtogroup USBDM_Group USBDM Peripheral Interface
 * @brief Hardware Peripheral Interface and library
 * @{
 */
/**
 * Used to configure pin-mapping before 1st use of peripherals
 */
void mapAllPins() {
#ifdef PCC_PCCn_CGC_MASK
      PCC->PCC_PORTA = PCC_PCCn_CGC_MASK;
      PCC->PCC_PORTB = PCC_PCCn_CGC_MASK;
      PCC->PCC_PORTC = PCC_PCCn_CGC_MASK;
      PCC->PCC_PORTD = PCC_PCCn_CGC_MASK;
#else
      enablePortClocks(PORTA_CLOCK_MASK|PORTB_CLOCK_MASK|PORTC_CLOCK_MASK|PORTD_CLOCK_MASK);
#endif
      PORTA->GPCHR = 0x8000UL|PORT_GPCHR_GPWE(0x000CUL);
      PORTA->GPCLR = 0x8200UL|PORT_GPCLR_GPWE(0x0006UL);
      PORTA->GPCLR = 0x8700UL|PORT_GPCLR_GPWE(0x0009UL);
      PORTB->GPCHR = 0x8100UL|PORT_GPCHR_GPWE(0x0002UL);
      PORTB->GPCLR = 0x8103UL|PORT_GPCLR_GPWE(0x000FUL);
      PORTB->GPCHR = 0x8103UL|PORT_GPCHR_GPWE(0x0001UL);
      PORTC->GPCLR = 0x8000UL|PORT_GPCLR_GPWE(0x0080UL);
      PORTC->GPCLR = 0x8100UL|PORT_GPCLR_GPWE(0x0066UL);
      PORTC->GPCLR = 0x8244UL|PORT_GPCLR_GPWE(0x0001UL);
      PORTC->GPCLR = 0x8400UL|PORT_GPCLR_GPWE(0x0018UL);
      PORTD->GPCLR = 0x8140UL|PORT_GPCLR_GPWE(0x0080UL);
      PORTD->GPCLR = 0x8203UL|PORT_GPCLR_GPWE(0x0008UL);
      PORTD->GPCLR = 0x8244UL|PORT_GPCLR_GPWE(0x0077UL);
}
/** 
 * End group USBDM_Group
 * @}
 */

} // End namespace USBDM

